version: '3'

services:
  compose-test:
    build: 
      context: .
      dockerfile: ./Dockerfile.compose
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
